### ISSUE TITLE
Support running arbitrary scripts at startup

### ISSUE THREAD

**Issue by mmh352** [mmh352/ou-container-content#1]
After distributing any content files, the ou-container-content should have the ability to run arbitrary scripts. This should support both inline and file scripts.

**Comment by psychemedia** [comment]
I noticed you've been pushing some commits relating to startup scripts; I have some things to push for the container I'm building (separate to ou-container-builder for SSU/TM351-21J where the solution I've had to come up with is to add the user to sudoers, eg:

```
RUN echo "$NB_USER ALL=(ALL:ALL) NOPASSWD: /sbin/service postgresql restart" >> /etc/sudoers && \
    echo "$NB_USER ALL=(ALL:ALL) NOPASSWD: /usr/bin/mongod" >> /etc/sudoers
```

and then in the start script, sudo the starts, eg:

```
sudo service postgresql restart
sudo mongod --fork --logpath /dev/stdout --dbpath ${MONGO_DB_PATH}
```

**Comment by mmh352** [comment]
That's the process that I follow as well. For services that are started via "/usr/sbin/service", all that needs listing is the service name. It partly handles the automatic generation of the necessary sudo files. For all other scripts, basically it follows the same approach as you listed. I'm looking into making the "sudo" bit a bit less work to setup for the user.

**Comment by psychemedia** [comment]
Something I'm not convinced about is the ability for commands in files to correctly pick up env vars. Sometimes they seem to be empty when I expect them to be populated (eg it seems that setting them via `ENV` in the Dockerfile is no guarantee? Or maybe I was doing something wrong elsewhere and misread the error:-(

**Comment by mmh352** [comment]
Strange that ENVs aren't being propagated. They should be, according to the docs.

**Comment by psychemedia** [comment]
Yeah.. I wondered if the shell things were running in may be part of the issue. Or whether it was another issue. Will check next week. Work related is no part of life for the next few days...
